--- # Simulation parameters
sim:
  data: ../../../../datasets/source2018_numeric_us_with_avro_order/
  outputFolder: ../../../../results/sim_us_dataset_behavior_comparison/periodC
  type: normal
  log: true
  window:
    start: 32
    stop: 48
  region: us
  cache:
    type: sizeSmall
    watermarks: true
    size:
      value: 200
      unit: T
    bandwidth: 
      value: 10
      redirect: true