--- # Simulation parameters
sim:
  data: ../../../../datasets/source2018_numeric_it_with_avro_order/
  outputFolder: ../../../../results/sim_italian_dataset_only_addition/100T
  type: normal
  window:
    start: 0
    stop: 52
  region: it
  cache:
    type: sizeBig
    watermarks: false
    size:
      value: 100
      unit: T
    bandwidth: 
      value: 10
      redirect: true