--- # Simulation parameters
sim:
  data: ../../datasets/source2018_numeric_it_with_avro_order/
  outputFolder: ../../results/sim_italian_dataset/cache_100T_10Gbit
  type: normal
  window:
    start: 0
    stop: 52
  region: it
  cache:
    type: lfu
    watermarks: false
    size:
      value: 100
      unit: T
    bandwidth: 
      value: 10
      redirect: true