# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: simService/simService.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='simService/simService.proto',
  package='simservice',
  syntax='proto3',
  serialized_options=_b('\n\031io.grpc.cache.sim.serviceB\017CacheSimServiceP\001'),
  serialized_pb=_b('\n\x1bsimService/simService.proto\x12\nsimservice\x1a\x1bgoogle/protobuf/empty.proto\"/\n\rSimCommonFile\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0c\n\x04size\x18\x02 \x01(\x02\"V\n\x0eSimCacheStatus\x12\x0f\n\x07hitRate\x18\x01 \x01(\x02\x12\x0c\n\x04size\x18\x02 \x01(\x02\x12\x13\n\x0bwrittenData\x18\x03 \x01(\x02\x12\x10\n\x08\x63\x61pacity\x18\x04 \x01(\x02\"1\n\rSimFileWeight\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0e\n\x06weight\x18\x02 \x01(\x02\x32\xcd\x02\n\nSimService\x12H\n\rSimServiceGet\x12\x19.simservice.SimCommonFile\x1a\x1a.simservice.SimCacheStatus\"\x00\x12G\n\x0fSimServiceClear\x12\x16.google.protobuf.Empty\x1a\x1a.simservice.SimCacheStatus\"\x00\x12T\n\x1bSimServiceGetInfoCacheFiles\x12\x16.google.protobuf.Empty\x1a\x19.simservice.SimCommonFile\"\x00\x30\x01\x12V\n\x1dSimServiceGetInfoFilesWeights\x12\x16.google.protobuf.Empty\x1a\x19.simservice.SimFileWeight\"\x00\x30\x01\x42.\n\x19io.grpc.cache.sim.serviceB\x0f\x43\x61\x63heSimServiceP\x01\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_SIMCOMMONFILE = _descriptor.Descriptor(
  name='SimCommonFile',
  full_name='simservice.SimCommonFile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='filename', full_name='simservice.SimCommonFile.filename', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='size', full_name='simservice.SimCommonFile.size', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=119,
)


_SIMCACHESTATUS = _descriptor.Descriptor(
  name='SimCacheStatus',
  full_name='simservice.SimCacheStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hitRate', full_name='simservice.SimCacheStatus.hitRate', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='size', full_name='simservice.SimCacheStatus.size', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='writtenData', full_name='simservice.SimCacheStatus.writtenData', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='capacity', full_name='simservice.SimCacheStatus.capacity', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=207,
)


_SIMFILEWEIGHT = _descriptor.Descriptor(
  name='SimFileWeight',
  full_name='simservice.SimFileWeight',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='filename', full_name='simservice.SimFileWeight.filename', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='weight', full_name='simservice.SimFileWeight.weight', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=209,
  serialized_end=258,
)

DESCRIPTOR.message_types_by_name['SimCommonFile'] = _SIMCOMMONFILE
DESCRIPTOR.message_types_by_name['SimCacheStatus'] = _SIMCACHESTATUS
DESCRIPTOR.message_types_by_name['SimFileWeight'] = _SIMFILEWEIGHT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SimCommonFile = _reflection.GeneratedProtocolMessageType('SimCommonFile', (_message.Message,), {
  'DESCRIPTOR' : _SIMCOMMONFILE,
  '__module__' : 'simService.simService_pb2'
  # @@protoc_insertion_point(class_scope:simservice.SimCommonFile)
  })
_sym_db.RegisterMessage(SimCommonFile)

SimCacheStatus = _reflection.GeneratedProtocolMessageType('SimCacheStatus', (_message.Message,), {
  'DESCRIPTOR' : _SIMCACHESTATUS,
  '__module__' : 'simService.simService_pb2'
  # @@protoc_insertion_point(class_scope:simservice.SimCacheStatus)
  })
_sym_db.RegisterMessage(SimCacheStatus)

SimFileWeight = _reflection.GeneratedProtocolMessageType('SimFileWeight', (_message.Message,), {
  'DESCRIPTOR' : _SIMFILEWEIGHT,
  '__module__' : 'simService.simService_pb2'
  # @@protoc_insertion_point(class_scope:simservice.SimFileWeight)
  })
_sym_db.RegisterMessage(SimFileWeight)


DESCRIPTOR._options = None

_SIMSERVICE = _descriptor.ServiceDescriptor(
  name='SimService',
  full_name='simservice.SimService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=261,
  serialized_end=594,
  methods=[
  _descriptor.MethodDescriptor(
    name='SimServiceGet',
    full_name='simservice.SimService.SimServiceGet',
    index=0,
    containing_service=None,
    input_type=_SIMCOMMONFILE,
    output_type=_SIMCACHESTATUS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SimServiceClear',
    full_name='simservice.SimService.SimServiceClear',
    index=1,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_SIMCACHESTATUS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SimServiceGetInfoCacheFiles',
    full_name='simservice.SimService.SimServiceGetInfoCacheFiles',
    index=2,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_SIMCOMMONFILE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SimServiceGetInfoFilesWeights',
    full_name='simservice.SimService.SimServiceGetInfoFilesWeights',
    index=3,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_SIMFILEWEIGHT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SIMSERVICE)

DESCRIPTOR.services_by_name['SimService'] = _SIMSERVICE

# @@protoc_insertion_point(module_scope)
