# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import simService_pb2 as simService_dot_simService__pb2


class SimServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SimGet = channel.unary_unary(
        '/simservice.SimService/SimGet',
        request_serializer=simService_dot_simService__pb2.SimCommonFile.SerializeToString,
        response_deserializer=simService_dot_simService__pb2.ActionResult.FromString,
        )
    self.SimClear = channel.unary_unary(
        '/simservice.SimService/SimClear',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=simService_dot_simService__pb2.SimCacheStatus.FromString,
        )
    self.SimClearFiles = channel.unary_unary(
        '/simservice.SimService/SimClearFiles',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=simService_dot_simService__pb2.SimCacheStatus.FromString,
        )
    self.SimClearHitMissStats = channel.unary_unary(
        '/simservice.SimService/SimClearHitMissStats',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=simService_dot_simService__pb2.SimCacheStatus.FromString,
        )
    self.SimGetInfoCacheStatus = channel.unary_unary(
        '/simservice.SimService/SimGetInfoCacheStatus',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=simService_dot_simService__pb2.SimCacheStatus.FromString,
        )
    self.SimDumps = channel.unary_stream(
        '/simservice.SimService/SimDumps',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=simService_dot_simService__pb2.SimDumpRecord.FromString,
        )
    self.SimLoads = channel.stream_unary(
        '/simservice.SimService/SimLoads',
        request_serializer=simService_dot_simService__pb2.SimDumpRecord.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )


class SimServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SimGet(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SimClear(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SimClearFiles(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SimClearHitMissStats(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SimGetInfoCacheStatus(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SimDumps(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SimLoads(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SimServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SimGet': grpc.unary_unary_rpc_method_handler(
          servicer.SimGet,
          request_deserializer=simService_dot_simService__pb2.SimCommonFile.FromString,
          response_serializer=simService_dot_simService__pb2.ActionResult.SerializeToString,
      ),
      'SimClear': grpc.unary_unary_rpc_method_handler(
          servicer.SimClear,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=simService_dot_simService__pb2.SimCacheStatus.SerializeToString,
      ),
      'SimClearFiles': grpc.unary_unary_rpc_method_handler(
          servicer.SimClearFiles,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=simService_dot_simService__pb2.SimCacheStatus.SerializeToString,
      ),
      'SimClearHitMissStats': grpc.unary_unary_rpc_method_handler(
          servicer.SimClearHitMissStats,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=simService_dot_simService__pb2.SimCacheStatus.SerializeToString,
      ),
      'SimGetInfoCacheStatus': grpc.unary_unary_rpc_method_handler(
          servicer.SimGetInfoCacheStatus,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=simService_dot_simService__pb2.SimCacheStatus.SerializeToString,
      ),
      'SimDumps': grpc.unary_stream_rpc_method_handler(
          servicer.SimDumps,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=simService_dot_simService__pb2.SimDumpRecord.SerializeToString,
      ),
      'SimLoads': grpc.stream_unary_rpc_method_handler(
          servicer.SimLoads,
          request_deserializer=simService_dot_simService__pb2.SimDumpRecord.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'simservice.SimService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
