--- # Simulation parameters
sim:
  data: ../../../../datasets/source2018_numeric_us_with_avro_order/
  outputFolder: ../../../../results/sim_us_dataset_no_k/500T
  type: normal
  window:
    start: 0
    stop: 52
  region: us
  overwrite: false
  cache:
    type: aiRL
    watermarks: false
    size:
      value: 500
      unit: T
    bandwidth: 
      value: 10
      redirect: true
  ai:
    rl:
      type: SCDL
      epsilon:
        decay: 0.000001
      addition:
        featuremap: ../../../../featureMaps/rlAdditionFeatureMap.json
