--- # Simulation parameters
sim:
  data: ../../../../datasets/source2018_numeric_it_with_avro_order/
  outputFolder: ../../../../results/sim_italian_dataset_behavior_comparison_double/periodA
  type: normal
  log: true
  window:
    start: 0
    stop: 12
  region: it
  cache:
    type: sizeSmall
    watermarks: true
    size:
      value: 200
      unit: T
    bandwidth:
      value: 10
      redirect: true
