--- # Simulation parameters
sim:
  data: ../../../../datasets/SizeFocusedDataset/
  outputFolder: ../../../../results/sim_syntethic_dataset/SizeFocusedDataset
  type: normal
  window:
    start: 0
    stop: 52
  region: it
  cache:
    type: sizeSmall
    watermarks: false
    size:
      value: 10
      unit: G
    bandwidth: 
      value: 1
      redirect: true