--- # Simulation parameters
sim:
  data: ../../../datasets/source2018_numeric_it_with_avro_order/
  outputFolder: ../../../results/sim_italian_dataset_with_watermars/cache_10T_10Gbit
  type: normal
  window:
    start: 0
    stop: 52
  region: it
  cache:
    type: lfu
    watermarks: true
    size:
      value: 10
      unit: T
    bandwidth: 
      value: 10
      redirect: true