--- # Simulation parameters
sim:
  data: ../../../../datasets/source2018_numeric_us_with_avro_order/
  outputFolder: ../../../../results/sim_us_dataset/1000T
  type: normal
  window:
    start: 0
    stop: 52
  region: us
  cache:
    type: sizeSmall
    watermarks: false
    size:
      value: 1000
      unit: T
    bandwidth: 
      value: 10
      redirect: true