--- # Simulation parameters
sim:
  data: ../../../../datasets/ExtremeBigSizeFocusedDataset/
  outputFolder: ../../../../results/sim_synthetic_dataset_with_watermarks/ExtremeBigSizeFocusedDataset
  type: normal
  window:
    start: 0
    stop: 52
  region: it
  overwrite: true
  cache:
    type: aiRL
    watermarks: true
    size:
      value: 100
      unit: G
    bandwidth:
      value: 10
      redirect: true
  ai:
    rl:
      type: SCDL
      epsilon:
        decay: 0.001
      addition:
        featuremap: ../../../../featureMaps/rlAdditionFeatureMap.json
