--- # Simulation parameters
sim:
  data: ../../../../datasets/source2018_numeric_it_with_avro_order/
  outputFolder: ../../../../results/sim_italian_dataset_behavior_comparison/periodC
  type: normal
  log: true
  window:
    start: 32
    stop: 48
  region: it
  cache:
    type: lfu
    watermarks: true
    size:
      value: 100
      unit: T
    bandwidth: 
      value: 10
      redirect: true