--- # Simulation parameters
sim:
  data: ../../../../datasets/source2018_numeric_it_with_avro_order/
  outputFolder: ../../../../results/sim_italian_dataset_behavior_comparison/periodC
  type: normal
  log: true
  window:
    start: 32
    stop: 48
  region: it
  overwrite: true
  cache:
    type: aiRL
    watermarks: false
    size:
      value: 100
      unit: T
    bandwidth: 
      value: 10
      redirect: true
  ai:
    rl:
      epsilon:
        decay: 0.00001
      addition:
        featuremap: ../../../../featureMaps/rlAdditionFeatureMap.json
      eviction:
        type: onFree
        featuremap: ../../../../featureMaps/rlEvictionFeatureMap.json
