# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pluginProto/pluginService.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pluginProto/pluginService.proto',
  package='pluginservice',
  syntax='proto3',
  serialized_options=_b('\n\034io.grpc.cache.plugin.serviceB\rPluginServiceP\001'),
  serialized_pb=_b('\n\x1fpluginProto/pluginService.proto\x12\rpluginservice\x1a\x1bgoogle/protobuf/empty.proto\":\n\x0b\x46ileRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0c\n\x04size\x18\x02 \x01(\x02\x12\x0b\n\x03hit\x18\x03 \x01(\x08\"+\n\x08\x46ileHint\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\r\n\x05store\x18\x02 \x01(\x08\x32\xd8\x01\n\rPluginService\x12@\n\x07GetHint\x12\x1a.pluginservice.FileRequest\x1a\x17.pluginservice.FileHint\"\x00\x12\x43\n\x0bUpdateStats\x12\x1a.pluginservice.FileRequest\x1a\x16.google.protobuf.Empty\"\x00\x12@\n\x0cResetHistory\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x42/\n\x1cio.grpc.cache.plugin.serviceB\rPluginServiceP\x01\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_FILEREQUEST = _descriptor.Descriptor(
  name='FileRequest',
  full_name='pluginservice.FileRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='filename', full_name='pluginservice.FileRequest.filename', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='size', full_name='pluginservice.FileRequest.size', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hit', full_name='pluginservice.FileRequest.hit', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=137,
)


_FILEHINT = _descriptor.Descriptor(
  name='FileHint',
  full_name='pluginservice.FileHint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='filename', full_name='pluginservice.FileHint.filename', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='store', full_name='pluginservice.FileHint.store', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=139,
  serialized_end=182,
)

DESCRIPTOR.message_types_by_name['FileRequest'] = _FILEREQUEST
DESCRIPTOR.message_types_by_name['FileHint'] = _FILEHINT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FileRequest = _reflection.GeneratedProtocolMessageType('FileRequest', (_message.Message,), {
  'DESCRIPTOR' : _FILEREQUEST,
  '__module__' : 'pluginProto.pluginService_pb2'
  # @@protoc_insertion_point(class_scope:pluginservice.FileRequest)
  })
_sym_db.RegisterMessage(FileRequest)

FileHint = _reflection.GeneratedProtocolMessageType('FileHint', (_message.Message,), {
  'DESCRIPTOR' : _FILEHINT,
  '__module__' : 'pluginProto.pluginService_pb2'
  # @@protoc_insertion_point(class_scope:pluginservice.FileHint)
  })
_sym_db.RegisterMessage(FileHint)


DESCRIPTOR._options = None

_PLUGINSERVICE = _descriptor.ServiceDescriptor(
  name='PluginService',
  full_name='pluginservice.PluginService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=185,
  serialized_end=401,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetHint',
    full_name='pluginservice.PluginService.GetHint',
    index=0,
    containing_service=None,
    input_type=_FILEREQUEST,
    output_type=_FILEHINT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateStats',
    full_name='pluginservice.PluginService.UpdateStats',
    index=1,
    containing_service=None,
    input_type=_FILEREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ResetHistory',
    full_name='pluginservice.PluginService.ResetHistory',
    index=2,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PLUGINSERVICE)

DESCRIPTOR.services_by_name['PluginService'] = _PLUGINSERVICE

# @@protoc_insertion_point(module_scope)
