--- # Simulation parameters
sim:
  data: ../../../../datasets/ExtremeBigSizeFocusedDataset/
  outputFolder: ../../../../results/sim_synthetic_dataset/ExtremeBigSizeFocusedDataset
  type: normal
  window:
    start: 0
    stop: 52
  region: it
  cache:
    type: sizeBig
    watermarks: false
    size:
      value: 100
      unit: G
    bandwidth:
      value: 10
      redirect: true
