// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ai.proto

package aiservice

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AIInput struct {
	InputVector          []float32 `protobuf:"fixed32,1,rep,packed,name=inputVector,proto3" json:"inputVector,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AIInput) Reset()         { *m = AIInput{} }
func (m *AIInput) String() string { return proto.CompactTextString(m) }
func (*AIInput) ProtoMessage()    {}
func (*AIInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_4bdfe6a5fd51d81f, []int{0}
}

func (m *AIInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AIInput.Unmarshal(m, b)
}
func (m *AIInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AIInput.Marshal(b, m, deterministic)
}
func (m *AIInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AIInput.Merge(m, src)
}
func (m *AIInput) XXX_Size() int {
	return xxx_messageInfo_AIInput.Size(m)
}
func (m *AIInput) XXX_DiscardUnknown() {
	xxx_messageInfo_AIInput.DiscardUnknown(m)
}

var xxx_messageInfo_AIInput proto.InternalMessageInfo

func (m *AIInput) GetInputVector() []float32 {
	if m != nil {
		return m.InputVector
	}
	return nil
}

type StorePrediction struct {
	Store                bool     `protobuf:"varint,1,opt,name=store,proto3" json:"store,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StorePrediction) Reset()         { *m = StorePrediction{} }
func (m *StorePrediction) String() string { return proto.CompactTextString(m) }
func (*StorePrediction) ProtoMessage()    {}
func (*StorePrediction) Descriptor() ([]byte, []int) {
	return fileDescriptor_4bdfe6a5fd51d81f, []int{1}
}

func (m *StorePrediction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorePrediction.Unmarshal(m, b)
}
func (m *StorePrediction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorePrediction.Marshal(b, m, deterministic)
}
func (m *StorePrediction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorePrediction.Merge(m, src)
}
func (m *StorePrediction) XXX_Size() int {
	return xxx_messageInfo_StorePrediction.Size(m)
}
func (m *StorePrediction) XXX_DiscardUnknown() {
	xxx_messageInfo_StorePrediction.DiscardUnknown(m)
}

var xxx_messageInfo_StorePrediction proto.InternalMessageInfo

func (m *StorePrediction) GetStore() bool {
	if m != nil {
		return m.Store
	}
	return false
}

func init() {
	proto.RegisterType((*AIInput)(nil), "aiservice.AIInput")
	proto.RegisterType((*StorePrediction)(nil), "aiservice.StorePrediction")
}

func init() { proto.RegisterFile("ai.proto", fileDescriptor_4bdfe6a5fd51d81f) }

var fileDescriptor_4bdfe6a5fd51d81f = []byte{
	// 186 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x48, 0xcc, 0xd4, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4c, 0xcc, 0x2c, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0x55,
	0xd2, 0xe6, 0x62, 0x77, 0xf4, 0xf4, 0xcc, 0x2b, 0x28, 0x2d, 0x11, 0x52, 0xe0, 0xe2, 0xce, 0x04,
	0x31, 0xc2, 0x52, 0x93, 0x4b, 0xf2, 0x8b, 0x24, 0x18, 0x15, 0x98, 0x35, 0x98, 0x82, 0x90, 0x85,
	0x94, 0xd4, 0xb9, 0xf8, 0x83, 0x4b, 0xf2, 0x8b, 0x52, 0x03, 0x8a, 0x52, 0x53, 0x32, 0x93, 0x4b,
	0x32, 0xf3, 0xf3, 0x84, 0x44, 0xb8, 0x58, 0x8b, 0x41, 0x42, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x1c,
	0x41, 0x10, 0x8e, 0x91, 0x2f, 0x17, 0xa7, 0xa3, 0x67, 0x30, 0xc4, 0x0a, 0x21, 0x07, 0x2e, 0x1e,
	0x47, 0x4f, 0xa8, 0x16, 0xff, 0xbc, 0x54, 0x21, 0x21, 0x3d, 0xb8, 0xf5, 0x7a, 0x50, 0xbb, 0xa5,
	0xa4, 0x90, 0xc4, 0xd0, 0xac, 0x50, 0x62, 0x70, 0xd2, 0xe1, 0x92, 0xc8, 0xcc, 0xd7, 0x4b, 0x2f,
	0x2a, 0x48, 0xd6, 0x4b, 0x4e, 0x4c, 0xce, 0x48, 0xd5, 0x4b, 0xcc, 0xd4, 0x83, 0xaa, 0x76, 0xe2,
	0x73, 0x06, 0x89, 0xc0, 0x6d, 0x0b, 0x60, 0x4c, 0x62, 0x03, 0x7b, 0xd2, 0x18, 0x10, 0x00, 0x00,
	0xff, 0xff, 0xea, 0x11, 0x20, 0xb6, 0xf0, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AIServiceClient is the client API for AIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AIServiceClient interface {
	// Make 1 prediction only
	AIPredictOne(ctx context.Context, in *AIInput, opts ...grpc.CallOption) (*StorePrediction, error)
}

type aIServiceClient struct {
	cc *grpc.ClientConn
}

func NewAIServiceClient(cc *grpc.ClientConn) AIServiceClient {
	return &aIServiceClient{cc}
}

func (c *aIServiceClient) AIPredictOne(ctx context.Context, in *AIInput, opts ...grpc.CallOption) (*StorePrediction, error) {
	out := new(StorePrediction)
	err := c.cc.Invoke(ctx, "/aiservice.AIService/AIPredictOne", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AIServiceServer is the server API for AIService service.
type AIServiceServer interface {
	// Make 1 prediction only
	AIPredictOne(context.Context, *AIInput) (*StorePrediction, error)
}

// UnimplementedAIServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAIServiceServer struct {
}

func (*UnimplementedAIServiceServer) AIPredictOne(ctx context.Context, req *AIInput) (*StorePrediction, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AIPredictOne not implemented")
}

func RegisterAIServiceServer(s *grpc.Server, srv AIServiceServer) {
	s.RegisterService(&_AIService_serviceDesc, srv)
}

func _AIService_AIPredictOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AIInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).AIPredictOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aiservice.AIService/AIPredictOne",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).AIPredictOne(ctx, req.(*AIInput))
	}
	return interceptor(ctx, in, info, handler)
}

var _AIService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "aiservice.AIService",
	HandlerType: (*AIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AIPredictOne",
			Handler:    _AIService_AIPredictOne_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ai.proto",
}
