--- # Simulation parameters
sim:
  data: ../../../../datasets/source2018_numeric_us_with_avro_order/
  outputFolder: ../../../../results/sim_us_dataset_behavior_comparison_double/periodB
  type: normal
  log: true
  window:
    start: 12
    stop: 24
  region: us
  cache:
    type: lru
    watermarks: true
    size:
      value: 400
      unit: T
    bandwidth:
      value: 10
      redirect: true
