--- # Simulation parameters
sim:
  data: ../../../../datasets/HighFrequencyDataset/
  outputFolder: ../../../../results/sim_synthetic_dataset/HighFrequencyDataset
  type: normal
  window:
    start: 0
    stop: 52
  region: it
  cache:
    type: aiRL
    watermarks: false
    size:
      value: 10
      unit: G
    bandwidth: 
      value: 1
      redirect: true
  ai:
    rl:
      epsilon:
        decay: 0.001
      addition:
         featuremap: ../../../../featureMaps/rlAdditionFeatureMap.json
      eviction:
        featuremap: ../../../../featureMaps/rlEvictionFeatureMap.json
