--- # Simulation parameters
sim:
  data: ../../../../datasets/source2018_numeric_it_with_avro_order/
  outputFolder: ../../../../results/sim_synthetic_dataset_with_watermarks/HighFrequencyDataset
  type: normal
  window:
    start: 0
    stop: 52
  region: it
  cache:
    type: lru
    watermarks: true
    size:
      value: 10
      unit: G
    bandwidth: 
      value: 1
      redirect: true