--- # Simulation parameters
sim:
  data: ../datasets/source2018_numeric_it_with_avro_order/
  outputFolder: ../results/sim_italian_dataset_TEST_SCDL
  type: normal
  cpuprofile: scdlProfiling.prof
  window:
    start: 0
    stop: 2
  region: it
  overwrite: true
  cache:
    type: aiRL
    watermarks: true
    size:
      value: 100
      unit: T
    bandwidth: 
      value: 10
      redirect: true
  ai:
    rl:
      type: SCDL
      # type: SCDL2
      epsilon:
        decay: 0.00001
      addition:
        featuremap: ../featureMaps/rlAdditionFeatureMap.json
      # eviction:
      #   type: onK
      #   k: 8192
      #   featuremap: ../featureMaps/rlEvictionFeatureMap.json
