// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pluginProto/pluginProto.proto

package pluginproto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FileRequest struct {
	Filename             string   `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Downloaded           float32  `protobuf:"fixed32,2,opt,name=downloaded,proto3" json:"downloaded,omitempty"`
	Hit                  bool     `protobuf:"varint,3,opt,name=hit,proto3" json:"hit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileRequest) Reset()         { *m = FileRequest{} }
func (m *FileRequest) String() string { return proto.CompactTextString(m) }
func (*FileRequest) ProtoMessage()    {}
func (*FileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_47ff7801c14f782c, []int{0}
}

func (m *FileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileRequest.Unmarshal(m, b)
}
func (m *FileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileRequest.Marshal(b, m, deterministic)
}
func (m *FileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileRequest.Merge(m, src)
}
func (m *FileRequest) XXX_Size() int {
	return xxx_messageInfo_FileRequest.Size(m)
}
func (m *FileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FileRequest proto.InternalMessageInfo

func (m *FileRequest) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *FileRequest) GetDownloaded() float32 {
	if m != nil {
		return m.Downloaded
	}
	return 0
}

func (m *FileRequest) GetHit() bool {
	if m != nil {
		return m.Hit
	}
	return false
}

type FileHint struct {
	Filename             string   `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Store                bool     `protobuf:"varint,2,opt,name=store,proto3" json:"store,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileHint) Reset()         { *m = FileHint{} }
func (m *FileHint) String() string { return proto.CompactTextString(m) }
func (*FileHint) ProtoMessage()    {}
func (*FileHint) Descriptor() ([]byte, []int) {
	return fileDescriptor_47ff7801c14f782c, []int{1}
}

func (m *FileHint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileHint.Unmarshal(m, b)
}
func (m *FileHint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileHint.Marshal(b, m, deterministic)
}
func (m *FileHint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileHint.Merge(m, src)
}
func (m *FileHint) XXX_Size() int {
	return xxx_messageInfo_FileHint.Size(m)
}
func (m *FileHint) XXX_DiscardUnknown() {
	xxx_messageInfo_FileHint.DiscardUnknown(m)
}

var xxx_messageInfo_FileHint proto.InternalMessageInfo

func (m *FileHint) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *FileHint) GetStore() bool {
	if m != nil {
		return m.Store
	}
	return false
}

func init() {
	proto.RegisterType((*FileRequest)(nil), "pluginproto.FileRequest")
	proto.RegisterType((*FileHint)(nil), "pluginproto.FileHint")
}

func init() { proto.RegisterFile("pluginProto/pluginProto.proto", fileDescriptor_47ff7801c14f782c) }

var fileDescriptor_47ff7801c14f782c = []byte{
	// 287 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x4d, 0x4b, 0xf4, 0x30,
	0x14, 0x85, 0x27, 0x33, 0xbc, 0xaf, 0xf5, 0xd6, 0x85, 0x04, 0x95, 0x52, 0x3f, 0x28, 0x5d, 0x75,
	0x63, 0x0a, 0xba, 0x12, 0x5c, 0xe8, 0x80, 0x1f, 0xcb, 0x12, 0x71, 0xe5, 0xaa, 0xd3, 0xde, 0xe9,
	0x04, 0x3a, 0x4d, 0x6c, 0x52, 0x65, 0x7e, 0xa4, 0xff, 0x49, 0x92, 0xce, 0x68, 0x41, 0xc7, 0x4d,
	0xc8, 0xb9, 0x1c, 0x9e, 0x7b, 0xcf, 0x81, 0x53, 0x55, 0x77, 0x95, 0x68, 0xb2, 0x56, 0x1a, 0x99,
	0x0e, 0xfe, 0x4c, 0xd9, 0x97, 0xfa, 0xfd, 0xc8, 0x89, 0xf0, 0xb8, 0x92, 0xb2, 0xaa, 0x31, 0x75,
	0x6a, 0xd6, 0xcd, 0x53, 0x5c, 0x2a, 0xb3, 0xea, 0x9d, 0xf1, 0x0b, 0xf8, 0xf7, 0xa2, 0x46, 0x8e,
	0xaf, 0x1d, 0x6a, 0x43, 0x43, 0xf0, 0xe6, 0xa2, 0xc6, 0x26, 0x5f, 0x62, 0x40, 0x22, 0x92, 0xec,
	0xf2, 0x2f, 0x4d, 0xcf, 0x00, 0x4a, 0xf9, 0xde, 0xd4, 0x32, 0x2f, 0xb1, 0x0c, 0xc6, 0x11, 0x49,
	0xc6, 0x7c, 0x30, 0xa1, 0xfb, 0x30, 0x59, 0x08, 0x13, 0x4c, 0x22, 0x92, 0x78, 0xdc, 0x7e, 0xe3,
	0x6b, 0xf0, 0x2c, 0xfc, 0x51, 0x34, 0x7f, 0x93, 0x0f, 0xe0, 0x9f, 0x36, 0xb2, 0x45, 0x07, 0xf5,
	0x78, 0x2f, 0x2e, 0x3e, 0x08, 0xf8, 0xd9, 0x77, 0x34, 0x7a, 0x05, 0x3b, 0x0f, 0x68, 0x1c, 0xec,
	0x90, 0x0d, 0x02, 0xb2, 0xcd, 0x8e, 0xf0, 0xf7, 0x71, 0x3c, 0xa2, 0xb7, 0xe0, 0x3f, 0xab, 0x32,
	0x37, 0xf8, 0x64, 0x72, 0xa3, 0x69, 0xf0, 0xc3, 0xb7, 0xce, 0x1f, 0x1e, 0xb1, 0xbe, 0x2c, 0xb6,
	0x29, 0x8b, 0xdd, 0xd9, 0xb2, 0xe2, 0x11, 0xbd, 0x81, 0x3d, 0x8e, 0xda, 0xee, 0xb7, 0xd7, 0xad,
	0xe8, 0x16, 0xe7, 0x76, 0xc2, 0xf4, 0x1c, 0x4e, 0x84, 0x64, 0x55, 0xab, 0x0a, 0x56, 0xe4, 0xc5,
	0x02, 0xd7, 0x47, 0x30, 0x8d, 0xed, 0x9b, 0x28, 0x70, 0x3a, 0x0c, 0x9b, 0x91, 0xd9, 0x7f, 0x07,
	0xb8, 0xfc, 0x0c, 0x00, 0x00, 0xff, 0xff, 0x9a, 0xc1, 0xd9, 0x1c, 0xeb, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PluginProtoClient is the client API for PluginProto service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PluginProtoClient interface {
	GetHint(ctx context.Context, in *FileHint, opts ...grpc.CallOption) (*FileHint, error)
	UpdateStats(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	ResetHistory(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
}

type pluginProtoClient struct {
	cc *grpc.ClientConn
}

func NewPluginProtoClient(cc *grpc.ClientConn) PluginProtoClient {
	return &pluginProtoClient{cc}
}

func (c *pluginProtoClient) GetHint(ctx context.Context, in *FileHint, opts ...grpc.CallOption) (*FileHint, error) {
	out := new(FileHint)
	err := c.cc.Invoke(ctx, "/pluginproto.PluginProto/GetHint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginProtoClient) UpdateStats(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/pluginproto.PluginProto/UpdateStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginProtoClient) ResetHistory(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/pluginproto.PluginProto/ResetHistory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginProtoServer is the server API for PluginProto service.
type PluginProtoServer interface {
	GetHint(context.Context, *FileHint) (*FileHint, error)
	UpdateStats(context.Context, *FileRequest) (*empty.Empty, error)
	ResetHistory(context.Context, *empty.Empty) (*empty.Empty, error)
}

// UnimplementedPluginProtoServer can be embedded to have forward compatible implementations.
type UnimplementedPluginProtoServer struct {
}

func (*UnimplementedPluginProtoServer) GetHint(ctx context.Context, req *FileHint) (*FileHint, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHint not implemented")
}
func (*UnimplementedPluginProtoServer) UpdateStats(ctx context.Context, req *FileRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStats not implemented")
}
func (*UnimplementedPluginProtoServer) ResetHistory(ctx context.Context, req *empty.Empty) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetHistory not implemented")
}

func RegisterPluginProtoServer(s *grpc.Server, srv PluginProtoServer) {
	s.RegisterService(&_PluginProto_serviceDesc, srv)
}

func _PluginProto_GetHint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileHint)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginProtoServer).GetHint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pluginproto.PluginProto/GetHint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginProtoServer).GetHint(ctx, req.(*FileHint))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginProto_UpdateStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginProtoServer).UpdateStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pluginproto.PluginProto/UpdateStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginProtoServer).UpdateStats(ctx, req.(*FileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginProto_ResetHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginProtoServer).ResetHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pluginproto.PluginProto/ResetHistory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginProtoServer).ResetHistory(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _PluginProto_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pluginproto.PluginProto",
	HandlerType: (*PluginProtoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHint",
			Handler:    _PluginProto_GetHint_Handler,
		},
		{
			MethodName: "UpdateStats",
			Handler:    _PluginProto_UpdateStats_Handler,
		},
		{
			MethodName: "ResetHistory",
			Handler:    _PluginProto_ResetHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pluginProto/pluginProto.proto",
}
