--- # Simulation parameters
sim:
  data: ../../../../../datasets/source2018_numeric_it_with_avro_order/
  outputFolder: ../../../../../results/sim_italian_dataset_with_watermarks_epsilon_test/fast/50T
  type: normal
  window:
    start: 0
    stop: 52
  region: it
  overwrite: true
  cache:
    type: aiRL
    watermarks: true
    size:
      value: 50
      unit: T
    bandwidth:
      value: 10
      redirect: true
  ai:
    rl:
      epsilon:
        decay: 0.001
      addition:
        featuremap: ../../../../../featureMaps/rlAdditionFeatureMap.json
      eviction:
        type: onK
        k: 8192
        featuremap: ../../../../../featureMaps/rlEvictionFeatureMap.json
