version: "3.7"

services:
  minio:
    image: minio/minio:RELEASE.2020-11-25T22-36-25Z
    network_mode: "host"
    volumes:
      - ${PATH_TO_MINIO_DATA}:/data
      - ./CAs/:/root/.minio/certs/CAs/
    environment:
      - MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
