--- # Simulation parameters
sim:
  data: ../../../../datasets/ExtremeSmallSizeFocusedDataset/
  outputFolder: ../../../../results/sim_synthetic_dataset_with_watermarks/ExtremeSmallSizeFocusedDataset
  type: normal
  window:
    start: 0
    stop: 52
  region: it
  cache:
    type: sizeSmall
    watermarks: true
    size:
      value: 100
      unit: G
    bandwidth:
      value: 10
      redirect: true
