--- # Simulation parameters
sim:
  data: ../../../datasets/source2018_numeric_us_with_avro_order/
  outputFolder: ../../../results/sim_us_dataset_with_watermars/cache_100T_10Gbit
  type: normal
  window:
    start: 0
    stop: 52
  region: it
  cache:
    type: aiRL
    watermarks: true
    size:
      value: 100
      unit: T
    bandwidth: 
      value: 10
      redirect: true
  ai:
    rl:
      epsilon:
        decay: 0.000001
      addition:
        featuremap: ../../../featureMaps/rlAdditionFeatureMap.json
      eviction:
        featuremap: ../../../featureMaps/rlEvictionFeatureMap.json
