--- # Simulation parameters
sim:
  data: ../../../datasets/source2018_numeric_it_with_avro_order/
  outputFolder: ../../../results/sim_infinite_cache
  type: normal
  window:
    start: 0
    stop: 52
  region: it
  overwrite: false
  cache:
    type: infinite
    watermarks: false
    size:
      value: 0
      unit: T
    bandwidth:
      value: 10
      redirect: true
