--- # Simulation parameters
sim:
  data: ../../../../datasets/source2018_numeric_us_with_avro_order/
  outputFolder: ../../../../results/sim_us_dataset_with_watermarks/200T
  type: normal
  window:
    start: 0
    stop: 52
  region: us
  cache:
    type: lfu
    watermarks: true
    size:
      value: 200
      unit: T
    bandwidth: 
      value: 10
      redirect: true